/**
 * Icon system — curated lucide icons, re-exported so screens import from one
 * place and never reach for emoji. `Icon` is a thin wrapper with sane defaults;
 * `domainIcon` maps fitness domains to their glyph.
 */

import {
  Activity,
  Apple,
  ArrowLeft,
  ArrowRight,
  ArrowLeftRight,
  BadgeCheck,
  AlertTriangle,
  Barcode,
  BarChart3,
  Beef,
  Bed,
  Bell,
  BellOff,
  BookOpen,
  Building2,
  Calculator,
  Calendar,
  Camera,
  SlidersHorizontal,
  Check,
  CheckCheck,
  ChefHat,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronsUpDown,
  CircleAlert,
  CircleCheck,
  CircleUser,
  ClipboardList,
  Clock,
  CloudOff,
  Copy,
  CreditCard,
  Croissant,
  Droplet,
  Droplets,
  Dumbbell,
  Ellipsis,
  ExternalLink,
  Flame,
  FlaskConical,
  Footprints,
  Gauge,
  Gift,
  Globe,
  GripVertical,
  Angry,
  Frown,
  Laugh,
  Meh,
  Heart,
  HeartPulse,
  Hand,
  History,
  Archive,
  Home,
  Image as ImageIcon,
  Upload,
  Wand2,
  Info,
  KeyRound,
  LogIn,
  LayoutGrid,
  LineChart,
  Leaf,
  LifeBuoy,
  List,
  ListChecks,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Moon,
  MoreHorizontal,
  Palette,
  PencilLine,
  Plug,
  Percent,
  Pill,
  Play,
  Plus,
  Minus,
  Ruler,
  Save,
  Scale,
  Salad,
  ScanLine,
  Search,
  Send,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Sliders,
  Smile,
  Soup,
  Star,
  Store,
  Sun,
  Tag,
  Target,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  Timer,
  RotateCcw,
  Trash2,
  TrendingUp,
  TrendingDown,
  Trophy,
  User,
  Users,
  UserPlus,
  Utensils,
  Wallet,
  Weight,
  Wheat,
  Wind,
  Waves,
  WifiOff,
  RefreshCw,
  Bike,
  Snowflake,
  X,
  Zap,
  type LucideIcon,
  // Sparkles is deliberately NOT re-exported. It had spread to ~20 screens as a
  // stand-in for "something happens here" — an empty media library, a free-trial
  // badge, progress photos, a passkey benefit, the notification fallback — none of
  // which are about sparkle. Where a surface is genuinely the studio's AI, it wears
  // that AI's avatar and name (`AiAvatar` / `useAiIdentity`), which the owner sets
  // in Branding; everywhere else it wears the icon for the thing it actually is.
  // lucide-react is a dependency of THIS package only, so leaving it out here is
  // the enforcement: there is no other door.
} from "lucide-react";

export type { LucideIcon };

export {
  Activity,
  Apple,
  ArrowLeft,
  ArrowRight,
  ArrowLeftRight,
  BadgeCheck,
  AlertTriangle,
  Barcode,
  BarChart3,
  Beef,
  Bed,
  Bell,
  BellOff,
  BookOpen,
  Building2,
  Calculator,
  Calendar,
  Camera,
  SlidersHorizontal,
  Check,
  CheckCheck,
  ChefHat,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronsUpDown,
  CircleAlert,
  CircleCheck,
  CircleUser,
  ClipboardList,
  Clock,
  CloudOff,
  Copy,
  CreditCard,
  Croissant,
  Droplet,
  Droplets,
  Dumbbell,
  Ellipsis,
  ExternalLink,
  Flame,
  FlaskConical,
  Footprints,
  Gauge,
  Gift,
  Globe,
  GripVertical,
  Angry,
  Frown,
  Laugh,
  Meh,
  Heart,
  HeartPulse,
  Hand,
  History,
  Archive,
  Home,
  ImageIcon,
  Upload,
  Wand2,
  Info,
  KeyRound,
  LogIn,
  LayoutGrid,
  LineChart,
  Leaf,
  LifeBuoy,
  List,
  ListChecks,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Moon,
  MoreHorizontal,
  Palette,
  PencilLine,
  Plug,
  Percent,
  Pill,
  Play,
  Plus,
  Minus,
  Ruler,
  Save,
  Scale,
  Salad,
  ScanLine,
  Search,
  Send,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Sliders,
  Smile,
  Soup,
  Star,
  Store,
  Sun,
  Tag,
  Target,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  Timer,
  RotateCcw,
  Trash2,
  TrendingUp,
  TrendingDown,
  Trophy,
  User,
  Users,
  UserPlus,
  Utensils,
  Wallet,
  Weight,
  Wheat,
  Wind,
  Waves,
  WifiOff,
  RefreshCw,
  Bike,
  Snowflake,
  X,
  Zap,
};

export type Domain = "activity" | "nutrition" | "sleep" | "cardio" | "hydration";

export const domainIcon: Record<Domain, LucideIcon> = {
  activity: Dumbbell,
  nutrition: Utensils,
  sleep: Moon,
  cardio: HeartPulse,
  hydration: Droplet,
};
