/**
 * GENERATES `src/brand/logos.ts` FROM `simple-icons`.
 *
 * ⚠️ NOBODY DRAWS A COMPANY'S LOGO BY HAND. The first attempt at this file was
 * three approximations written from memory — a cloud, a letter and a four-colour
 * G — which is a trademark reproduced wrongly, on a screen that names the company
 * it belongs to. `simple-icons` is the maintained set of official brand paths and
 * official brand colours, CC0, and the generation is committed so the browser
 * ships four paths rather than a package of three thousand files.
 *
 * ⚠️ RUN IT AGAIN TO ADD ONE: `node dev/logos.mjs`. The list below is the only
 * thing to edit, and a name it cannot resolve is a hard failure rather than a
 * silently missing logo.
 *
 * ⚠️ NOT SHIPPED CODE. This runs in Node, at development time, and nothing in
 * `src` imports it.
 */

import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const icons = require("simple-icons");

/** The mark name a manifest declares, and the icon it resolves to. */
const WANTED = [
  ["cloudflare", "siCloudflare"],
  ["stripe", "siStripe"],
  ["google", "siGoogle"],
];

const rows = WANTED.map(([name, key]) => {
  const icon = icons[key];
  if (!icon) throw new Error(`simple-icons has no ${key}`);
  return { name, title: icon.title, hex: `#${icon.hex}`, path: icon.path };
});

const body = rows.map((r) =>
  `  ${JSON.stringify(r.name)}: { title: ${JSON.stringify(r.title)}, hex: ${JSON.stringify(r.hex)}, path: ${JSON.stringify(r.path)} },`,
).join("\n");

writeFileSync("src/brand/logos.ts", `/**
 * SOMEBODY ELSE'S LOGO — official paths, official colours, generated.
 *
 * ⚠️ GENERATED BY \`node dev/logos.mjs\`. Do not edit: add a name to that file's
 * list and run it. Every path and colour below is the company's own, from
 * \`simple-icons\` (CC0) — because a logo drawn from memory is a trademark
 * reproduced wrongly, on the one screen that names the company it belongs to.
 *
 * ⚠️ FOUR PATHS RATHER THAN A DEPENDENCY. The package is three thousand files;
 * what the browser needs is the handful this deployment's processors actually
 * declare, so the generation is committed and the package stays in devDependencies.
 *
 * ⚠️ ONE VIEWBOX FOR ALL OF THEM: 0 0 24 24, which is what the source draws in.
 */

export interface Logo {
  /** The company's own name for it. Never rendered — the row carries the name. */
  readonly title: string;
  /** Their published brand colour. */
  readonly hex: string;
  /** One path, at 24 units. */
  readonly path: string;
}

export const LOGOS: Readonly<Record<string, Logo>> = {
${body}
};
`);

console.log(`wrote src/brand/logos.ts — ${rows.length} logos`);
