/**
 * THE ICON GENERATOR — lucide's geometry, into one checked-in file.
 *
 * ⚠️ NOT SHIPPED CODE. It writes `src/icons.ts`, which IS shipped, and
 * `test/icons.test.ts` re-derives the same thing from `lucide-static` and
 * compares — so the generated file cannot silently drift from the package it
 * came from, and a hand-edit to a path is a test failure rather than a glyph
 * that is subtly not the one everybody else's product uses.
 *
 * ⚠️ THE GEOMETRY IS COPIED RATHER THAN IMPORTED, deliberately. `@one/ui` is
 * imported by workers that render on the server; a runtime dependency on an icon
 * package is a dependency in every one of them, for twenty-two shapes that never
 * change. The licence is ISC and the attribution is in the generated header.
 *
 * Run: tsx reference/build-icons.ts   (from platform/ui)
 */

import { readFileSync, writeFileSync } from "node:fs";

/**
 * ⚠️ OUR NAMES, IN THEIRS — the same shape as `borrowed.ts`, for the same
 * reason. A component says `chart`; which lucide file that is, is one line here.
 */
export const FROM_LUCIDE: Readonly<Record<string, string>> = {
  plus: "plus",
  send: "send",
  box: "package",
  dots: "ellipsis",
  shield: "shield",
  key: "key-round",
  phone: "smartphone",
  clock: "clock",
  mail: "mail",
  users: "users",
  lock: "lock",
  search: "search",
  dumbbell: "dumbbell",
  apple: "apple",
  chart: "chart-column",
  camera: "camera",
  image: "image",
  list: "list",
  back: "arrow-left",
  close: "x",
  chevron: "chevron-right",
  bell: "bell",
};

/**
 * The drawing instructions only — the wrapper is the component's.
 *
 * ⚠️ THE OPENING TAG IS FOUND FROM `<svg`, NOT FROM THE FIRST `>`. Every file
 * starts with a licence comment, so the first `>` in it closes THAT — and the
 * extracted "geometry" then carries a whole svg element with its own width,
 * stroke and class, nested inside ours. It renders, at the wrong size, wearing
 * the library's class.
 */
export const geometry = (lucideName: string): string => {
  const svg = readFileSync(`node_modules/lucide-static/icons/${lucideName}.svg`, "utf8");
  const open = svg.indexOf(">", svg.indexOf("<svg"));
  return svg.slice(open + 1, svg.lastIndexOf("</svg>")).replace(/\s*\n\s*/g, "").trim();
};

const rows = Object.entries(FROM_LUCIDE)
  .map(([ours, theirs]) => `  ${ours}: ${JSON.stringify(geometry(theirs))},`)
  .join("\n");

const file = `/**
 * THE ICONS — lucide's geometry, and our names for it.
 *
 * ⚠️ GENERATED by \`reference/build-icons.mjs\`; \`test/icons.test.ts\` re-derives
 * it from \`lucide-static\` and compares. A hand-edited path is a test failure
 * rather than a glyph that is subtly not the one every other product draws.
 *
 * ⚠️ THE SET IS CLOSED, LIKE EVERY OTHER LIST IN THIS PACKAGE. lucide ships two
 * thousand icons; a product that can reach all of them has no icon language, it
 * has a search box. Adding one is an edit to the map in the generator, on
 * purpose, in review.
 *
 * Icons from lucide (https://lucide.dev), ISC licence. The geometry is COPIED
 * rather than imported: this package is loaded by workers rendering on a server,
 * and a runtime dependency for twenty-two shapes that never change is a
 * dependency in every one of them.
 */

/** ⚠️ Our name → the drawing. The wrapper, the size and the colour are not here. */
export const ICONS = {
${rows}
} as const;

export type IconName = keyof typeof ICONS;
export const ICON_NAMES = Object.keys(ICONS) as readonly IconName[];
`;

writeFileSync("src/icons.ts", file);
console.log(`wrote src/icons.ts — ${Object.keys(FROM_LUCIDE).length} icons, ${(file.length / 1024).toFixed(1)} kB`);
